### ISSUE TITLE
a javascript error occurred in the main process

### ISSUE THREAD

**Issue by fandean** [plotly/falcon#533]
### The following error occurred when opening Falcon.

![image](https://user-images.githubusercontent.com/25637720/48697109-c5698100-ec1e-11e8-998d-a9ad34d045b5.png)

> falcon install 
> ```
> scoop install falcon-sql-client
> ```
> Win10 64x

**Comment by grenzi** [comment]
![2018-11-21_12-10-34](https://user-images.githubusercontent.com/2512673/48860459-953cf200-ed86-11e8-8342-8ad5bda00bc9.png)

similar error. windows 10 enterprise x64, v 1803 (OS Build 17134.228). same error occurs when running as admin.

**Comment by chintanpbhatt** [comment]
The same error on Windows 10 Pro Ver 1803 OSBuild 17134.345,  x64 bit OS & processor

**Comment by nicolaskruchten** [comment]
This should now be resolved with version 4.0.0, which I've just released. You can use the download links at https://plot.ly/free-sql-client-download/

**Comment by olusolaxx** [comment]
The issue is still occurring. It has not been resolved. Query and Schedule tabs are not responsive. Plotly tab missing. Version 4.1.0
